[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
JuliaBUGS = "ba9fb4c0-828e-4473-b6a1-cd2560fee5bf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[coinfer]
entrance_file = "model.jl"
