name = "Coinfer"
uuid = "2494631e-bceb-4539-8821-5341beee86e1"
version = "0.0.2"
authors = ["coinfer.ai"]

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
TuringCallbacks = "ea0860ee-d0ef-45ef-82e6-cc37d6be2f9c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
OnlineStats = "1.7.2"
OnlineStatsBase = "1.7.1"
